### ISSUE TITLE
Google Static Map issue

### ISSUE THREAD

**Issue by tansor** [mitroadmaps/roadtracer#12]
Hi there. I have got an Google Static Map Api Key while I'm following the steps to construct the dataset, however, Google always return a 403 code to the url request. Can you figure that out?

Things like:
https://maps.googleapis.com/maps/api/staticmap?center=48.863665,2.309677&zoom=18&size=576x576&maptype=satellite&key=MY_API_KEY

And I have also tried SIGNATURE by adding '&signature=MY_SIGNATURE_CODE', which didn't make sense.

**Comment by uakfdotb** [comment]
You don't need the signature but now you need to enable billing on Google Cloud before it'll let you use the API. The first $200/mo in Maps/Routes/Places API requests is free according to https://cloud.google.com/maps-platform/pricing/.
