### ISSUE TITLE
2_mkgraphs.go 

### ISSUE THREAD

**Issue by tansor** [mitroadmaps/roadtracer#13]
Hi, I was following the steps to construct dataset. I have downloaded planet.osm.pbf. However, when I run code like following:
```
mkdir /data/rawgraphs/
go run 2_mkgraphs.go /data/planet.osm.pbf /data/rawgraphs/
```
I got an error like following: (regionMap only contains 'boston' because I commented all other cities in 'regions.go')
```
boston: {{-71.22041986328126 42.27112988585102} {-70.99794671875001 42.43553834545579}}
finished 10M vertices
finished 20M vertices
finished 30M vertices
finished 40M vertices
..........
finished 4690M vertices
finished 100K ways
finished 200K ways
finished 300K ways
finished 400K ways
finished 500K ways
finished 600K ways
finished 700K ways
..........
finished 98700K ways
finished 98800K ways
finished 98900K ways
panic: json: unsupported type: map[int]bool

goroutine 1 [running]:
panic(0x7f8240, 0xc84d007550)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.main.func1(0xc820032088, 0x1, 0x1, 0xc820051b70, 0x7fff04eaf139, 0x11, 0xc820018400, 0x1, 0x1)
	/home/tyq/Dev/RoadTracer/roadtracer/dataset/2_mkgraphs.go:53 +0xd2
main.main()
	/home/tyq/Dev/RoadTracer/roadtracer/dataset/2_mkgraphs.go:58 +0xd41
exit status 2
```
It only generates 'boston.graph' without json file.
And, It's too slow to get the result (About one or two hour per city?)
Can you figure that out?

**Comment by uakfdotb** [comment]
It needs go 1.8 or later. For the slowness, it can generate all the cities in one pass, so the two hours is independent of number of cities. If you want it to be faster, instead of using planet.osm.pbf, you can use a smaller region, e.g. https://download.geofabrik.de/north-america/us/massachusetts.html

To find region start from https://download.geofabrik.de/
