### ISSUE TITLE
Getting Inaccurate Results while executing roadtracer on a different dataset

### ISSUE THREAD

**Issue by ahanagemini** [mitroadmaps/roadtracer#22]
We have tried to train roadtracer on 2500*2500 pixel images after generating the start_locations. The start_locations do lie on the roads when visualized on the input images.
We train using the following:
osm graphs as ground truth
tile size =2500
window size = 256
We use only 15 tiles for training and try to achieve overfitting by checking with validation tile after every 2500 iterations and taking outer_it in range 0 to 15.
MAX_PATH_LENGTH = 8192
SEGMENT_LENGTH = 40
PARALLEL_TILES = 20
SAVE_ITERATIONS = 1024
PATHS_PER_TILE_AXIS = 1
DETECT_MODE = 'normal'
WINDOW_SIZE = 256
FOLLOW_TARGETS = False
THRESHOLD = 0.4
SINGLE_ANGLE_TARGET = False

Then, we do inference on the same set of images that we train on with the following parameters:
MAX_PATH_LENGTH = 2048
SEGMENT_LENGTH = 40
PATHS_PER_TILE_AXIS = 1
TILE_MODE = 'sat'
EXISTING_GRAPH_FNAME = None
DETECT_MODE = 'normal'
THRESHOLD_BRANCH = 0.4
THRESHOLD_FOLLOW = 0.4
WINDOW_SIZE = 256
SAVE_EXAMPLES = False
FOLLOW_TARGETS = False

On visualizing the images, we see that the results are not accurate. I am providing some sample outputs that we got. The red lines are the predicted roads when we start from a single randomly selected start location.
![48298_0](https://user-images.githubusercontent.com/15112797/50299431-8ca40e00-044f-11e9-9c69-259598c078da.png)
![48298_1](https://user-images.githubusercontent.com/15112797/50299432-8ca40e00-044f-11e9-8674-fe9ff6cdd26f.png)
![48298_9](https://user-images.githubusercontent.com/15112797/50299433-8ca40e00-044f-11e9-89d5-212252f15543.png)
![48298_12](https://user-images.githubusercontent.com/15112797/50299434-8ca40e00-044f-11e9-8718-288736873487.png)

Please tell us what might be wrong with the way in which we have trained and tested roadtracer.

**Comment by uakfdotb** [comment]
The imagery doesn't look that different from the one from RoadTracer dataset so I think first step to debug it might be to see what the inference result is when using the pre-trained model (https://mapster.csail.mit.edu/roadtracer/model.zip).

**Comment by ahanagemini** [comment]
Thanks a lot. We had issue with the row and column of the .graph being inverse what is expected by roadtracer. We are getting some results that covers the roads partially now.

**Comment by ahanagemini** [comment]
We have got results from RoadTracer by using one edge for each connected component of the ground truth as the partial graph which is input to infer.py. However, our results are not good. Is there some other way in which this should be done? If we select more number of edges from the ground truth per connected component, is that expected to give better results?

**Comment by uakfdotb** [comment]
The starting locations approach is designed to improve for weakly connected components. So e.g. in NYC there was one connected component but with a high threshold RoadTracer had difficulty traversing bridges from one side if the water body to the other.

The approach we used was to first run a segmentation approach on the entire imagery, call the output G (use a high threshold to generate G so that G only contains high confidence edges). Pick highest confidence edge from G, run RoadTracer from that graph, get a partial output H. Then remove any edge in G that is within some distance (like 64 pixels) to an edge in H. If there is anything remaining in G, then pick highest confidence edge and start RoadTracer again.

**Comment by uakfdotb** [comment]
BTW recently we developed improved version of RoadTracer that has similar performance but it is much easier to train. It is here: https://github.com/mitroadmaps/MAiD

https://mapster.csail.mit.edu/maid/maid.pdf
