### ISSUE TITLE
ordering of row, column in the vertices section of .graph file

### ISSUE THREAD

**Issue by bparaj** [mitroadmaps/roadtracer#23]
While writing out the ground truth graph as .graph file, we are ordering the vertices section as follows:

     row column

where, (row, column) is the pixel position in numpy terms with origin as the top-left corner of the image. So, a vertex with values (3, 6) will correspond to row position 3 and column position 6 from the top-left.

You do mention about the ordering in the following comment but I was still confused about which one was row/column:
https://github.com/mitroadmaps/roadtracer/issues/11#issuecomment-417822896

Are we doing it wrong?

P.S. We have one tile per region.

**Comment by uakfdotb** [comment]
I think my earlier comment is incorrect.

(0, 0) should be bottom left of imagery and it should be (column, row).

**Comment by bparaj** [comment]
Does it mean we need to change line 97 in `utils/mapextract.py` to the following?

    f.write('{} {}\n'.format(vertex[1], vertex[0]))

Will this be sufficient or do we also need to transform to account for the fact that bottom-left is (0,0) instead of the top-left?

**Comment by bparaj** [comment]
Sorry. I just realized there's `im = numpy.swapaxes(im, 0, 1)` and the above modification is not required.

I am still not sure if any other coordinate transformation is required.
