### ISSUE TITLE
1_sat.go can't work

### ISSUE THREAD

**Issue by 4ever-Rain** [mitroadmaps/roadtracer#27]
Hi, I was following the steps to construct dataset.  However, when I run the code like the following:

```
mkdir /data/imagery/
go run 1_sat.go MyAPIKEY /data/imagery/
```
I got an error like the following: 
`panic: open /data/imagery/XXX_-X_-X_sat.png: no such file or directory`
ex. open /data/imagery/austin_-1_-1_sat.png: no such file or directory

I checked the folder of imagery. It was empty.

How can I solve this problem?
@uakfdotb

**Comment by uakfdotb** [comment]
Create the directory /data/imagery/.

**Comment by 4ever-Rain** [comment]
Thanks for your help! It have worked now, after I get the permission or change the path.
