### ISSUE TITLE
panic: open /data/rawgraphs//paris.graph: no such file or directory

### ISSUE THREAD

**Issue by Lunabig** [mitroadmaps/roadtracer#28]
By running the command: go run 2_mkgraphs.go /data/planet.osm.pbf /data/rawgraphs/, such error happened to me.

panic: open /data/rawgraphs//paris.graph: no such file or directory

I try to update the go to go version go1.9 linux/amd64; it doesn't help, the same problem happened again.

 I download the planet-latest.osm.pbf and manually change it name to planet.osm.pbf.

Can you help me ?

**Comment by uakfdotb** [comment]
Try mkdir /data/rawgraphs before running 2_mkgraphs.go. Or instead of /data/rawgraphs specify a directory that exists.

**Comment by Lunabig** [comment]
I try to specify a directory for both directories. It works. Thank u for your help!!!
