### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by fablion** [mitroadmaps/roadtracer#32]
HI,
I try to use roadtracer for the first time.
I'm a Archlinux user, using Anaconda with Python2.7.

Here is the terminal output. 
https://pastebin.com/BvhFdkUS

Do you understand the error? There is no reason to look in /home/ubuntu. This folder doesn't exist!

Thanks

Regards

Fabien

**Comment by uakfdotb** [comment]
You can either create the directory /home/ubuntu/data/ or set SAVE_EXAMPLES=False in train.py.
