### ISSUE TITLE
Question about training duration

### ISSUE THREAD

**Issue by fablion** [mitroadmaps/roadtracer#33]
Hi again,
I start training on my desktop yesterday evening. Only 18 step have been finished in 1 day.

Is it normal? Is there any way to speed the training process? Or my desktop is too weak?

Thanks

Fabien

My configuration:
16Go of RAM with 32 Go swap (under Linux distribution Solus -64 bits)
CPU: Intel Core i5-4690K (4*3.50GHz)
GeForce GT740

**Comment by uakfdotb** [comment]
We can run 100+ steps per day on V100 GPU. Perhaps it is not using the GPU or the GPU is not fast enough.
