### ISSUE TITLE
batch input size inconsistency

### ISSUE THREAD

**Issue by iliadsouti** [mitroadmaps/roadtracer#6]
Hi,

When in training, there is a problem of input batch inconsistency:
ValueError: Cannot feed value of shape (4, 256, 256, 5) for Tensor u'Placeholder_1:0', which has shape '(?, 256, 256, 3)'

How can it be solved?

**Comment by uakfdotb** [comment]
Hi, sorry for the very slow response, I did not see this until now.

I think there is a bug in tileloader.py on line 230 (def num_input_channels). If you change return 3 to return 5 it should work.

I will update it after testing.

**Comment by uakfdotb** [comment]
fixed in dfd64e09f2df6902092d12ae9c32e9ac6a6ce5e7
